# Generated by Django 4.0.6 on 2022-11-01 08:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='time',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
